const PROCESSING_STATUS = {
    UPLOADED: "UPLOADED",
    OCR_COMPLETE: "OCR_COMPLETE",
    AI_PROCESSED: "AI_PROCESSED",
    FAILED: "FAILED",
}

const APPROVAL_STATUS = {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED"
}

module.exports = {PROCESSING_STATUS, APPROVAL_STATUS }